---
- hosts: vault-server
  remote_user: ubuntu
  become: yes 
  tasks:
  - name: Adicionando as chaves do repo Hashicorp
    apt_key: 
      url: https://apt.releases.hashicorp.com/gpg
      state: present

  - name: Add Hashicorp Vault Repo
    shell: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

  - name: Install Vault
    apt:
      name: vault
      update_cache: yes

  - name: Create vault config directory
    file: state=directory path=/home/ubuntu/vault/

  - name: Copy vault config to server
    copy: src=config.hcl dest=/home/ubuntu/vault/config.hcl

  - name: Copy Unseal Script
    copy: src=unseal.sh dest=/home/ubuntu/vault    
  
  
